---
abstract: 'A Metabase relay server component'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: '6.42'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0.47'
configure_requires:
  ExtUtils::MakeMaker: '6.42'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: POE-Component-Metabase-Relay-Server
requires:
  CPAN::Testers::Report: '1.999'
  DBD::SQLite: '1.29'
  DBI: '1.609'
  Data::UUID: '1.203'
  JSON: '2.17'
  JSON::XS: '2.29'
  Metabase::Fact: '0.011'
  Metabase::User::Profile: '0.003'
  Metabase::User::Secret: '0.003'
  Moose: '1.01'
  Moose::Util::TypeConstraints: '1.01'
  MooseX::POE: '0.205'
  MooseX::Types::Path::Class: '0.05'
  MooseX::Types::URI: '0.03'
  POE: '1.299'
  POE::Component::Client::HTTP: '0.942'
  POE::Component::EasyDBI: '1.23'
  POE::Component::Metabase::Client::Submit: '0.12'
  POE::Component::Resolver: '0.911'
  Params::Util: '1.01'
  Storable: '0'
  Test::POE::Server::TCP: '1.12'
  Time::HiRes: '0'
  URI: '1.52'
  perl: v5.6.0
resources:
  homepage: https://github.com/bingos/poe-component-metabase-relay-server
  repository: https://github.com/bingos/poe-component-metabase-relay-server.git
version: '0.28'
